---
title: "Assignment - Lecture 09: Project Heart"
author: "Ann-Sophie Frind and Catherine Rohner"
date: "2024-05-08"
output: html_document
editor_options: 
  markdown: 
    wrap: sentence
---

### Format

The project can for example be:

-   Re-producing the analyses from a publication (in a critical fashion)

-   Analyzing new data (e.g. yours or in collaboration with a group)

-   Exploring the differences between a given set of TFs

-   Anything you think of which involves competences developed in the course

# What is the topic?

We will use Histone ChIP-seq and ATAC-seq data to study key histone modifications (H3K4me1, H3K9me3, and H3K27ac) and chromatin accessibility in the heart's left ventricle.
These studies are essential for understanding how genes are regulated in heart development and disease.
Our research aims to discover how these epigenetic markers influence heart health, particularly across different ages and genders.

1.  **H3K4me1:**

    -   **Role:** Primarily found at enhancers, H3K4me1 boosts gene transcription from a distance, interacting with promoters via looping mechanisms.
        Enhancers found in combination with H3K27ac are usually particularly active ones.

    -   **Relevance:** Important for understanding regulatory elements that might be activated or repressed in an age-dependent manner or between genders in cardiac tissues.

2.  **H3K9me3**:

    -   **Role:** Typically associated with heterochromatin and transcriptional repression.
        Is prevalent in regions like centromeres and telomeres, contributing to genome stability and gene silencing.

    -   **Relevance:** Essential for understanding gene repression processes that are influenced by age or gender, which could impact cardiac function and disease risk.

3.  **H3K27ac**:

    -   **Role:** H3K27ac marks active enhancers and promoters, indicating regions of active transcription.

    -   **Relevance:** This modification helps identify gene activation sites crucial for cardiac function, offering insights into how gene regulation changes with age or differs between genders in heart tissues.

4.  **ATAC-seq**:

    -   **Role:** ATAC-seq identifies open chromatin areas accessible to transcription factors.

    -   **Relevance:** Essential for understanding regulatory dynamics in cardiac function, highlighting how gene accessibility varies with age and gender.

### Age-Related Differences:

-   **Objective:** Explore how aging influences the epigenetic landscape by comparing younger and older individuals, aiming to identify age-related changes linked to cardiac function decline.

-   **Methodology:** Compare histone profiles and chromatin accessibility in younger (34-year-old males and 46-year-old females) versus older adults (73-year-old males and 59-year-old females).

### Gender-Specific Differences:

-   **Objective:** Examine potential differences in epigenetic regulation between male and female left ventricular tissues, to identify gender-specific factors that influence cardiac disease risk.

-   **Methodology:** Analyze and compare the histone profiles and chromatin accessibility across genders to determine varaitions in epigenetic regulation in male versus female cardiac tissues.

# What data will we be using?

We will probably be using these data: <https://www.encodeproject.org/search/?type=Experiment&control_type!=*&status=released&perturbed=false&assay_title=ATAC-seq&assay_title=Histone+ChIP-seq&biosample_ontology.term_name=heart+left+ventricle>

### Old male (73y)

ATAC-seq: <https://www.encodeproject.org/experiments/ENCSR769DGC/>\
H3K4me1: <https://www.encodeproject.org/experiments/ENCSR461MTO/>\
H3K9me3: <https://www.encodeproject.org/experiments/ENCSR843ETK/>\
H3K27ac: <https://www.encodeproject.org/experiments/ENCSR402JWL/>\

### Young male (34y)

ATAC-seq(43y): <https://www.encodeproject.org/experiments/ENCSR310RJN/>\
H3K4me1: <https://www.encodeproject.org/experiments/ENCSR111WGZ/>\
H3K9me3: <https://www.encodeproject.org/experiments/ENCSR176KNR/>\
H3K27ac: <https://www.encodeproject.org/experiments/ENCSR150QXE/>\

### Old female (59y)

ATAC-seq: <https://www.encodeproject.org/experiments/ENCSR925LGW/>\
H3K4me1: <https://www.encodeproject.org/experiments/ENCSR485LPA/>\
H3K9me3: <https://www.encodeproject.org/experiments/ENCSR284DWQ/>\
H3K27ac: <https://www.encodeproject.org/experiments/ENCSR884SIF/>\

### Young female(46y)

ATAC-seq(47y): <https://www.encodeproject.org/experiments/ENCSR399OSE/>\
ATAC-seq(42y): <https://www.encodeproject.org/experiments/ENCSR593YFB/>\
H3K4me1: <https://www.encodeproject.org/experiments/ENCSR848BXL/>\
H3K9me3: <https://www.encodeproject.org/experiments/ENCSR433LHD/>\
H3K27ac: <https://www.encodeproject.org/experiments/ENCSR863BVD/>\

# What are the analyses you wish to reproduce, or the questions you wish to answer?

Generally, the literature suggests that men are generally at higher risk of certain cardiovascular diseases than women.
Also, the risk generally increases with age.
Therefore, we want to see whether we can find differences in the chosen histone modifications between the groups.

1.  **Differential Peak Calling**: Compare peak data between age groups (young vs. old) and between sexes to identify differential binding or chromatin accessibility patterns.

    → Hypothesis: In left ventricle tissue, older individuals have a higher prevalence of H3K9me3 peaks in regions associated with cardiac muscle contraction genes compared to younger individuals, leading to repressive chromatin states and reduced expression of these genes.This differential repressive binding contributes to age-related cardiac functional decline.\
    → Hypothesis: Females exhibit higher chromatin accessibility (ATAC-seq peaks) at H3K4me1-marked enhancers in regions regulating estrogen-responsive genes than males, influencing sex-specific protective effects on cardiac function.

2.  **Gene Association**: Map histone peaks to the nearby genes or regulatory regions like promoters and enhancers.

    → Hypothesis: Differential H3K4me1 peaks in young vs. old LV tissues are associated with genes involved in oxidative stress response and energy metabolism, implicating age-related enhancer changes in declining mitochondrial function and increased oxidative damage.
    This differential repressive binding contributes to age-related cardiac functional decline.\
    → Hypothesis: Differential H3K9me3 peaks between males and females are linked to genes that regulate inflammatory pathways, suggesting sex-specific repression of pro-inflammatory genes.

3.  **Motif Discovery**: Analyze enriched transcription factor binding motifs in age- or sex-specific peaks.

    → Hypothesis: Age-related H3K4me1 peaks in the LV are enriched for motifs of stress-responsive transcription factors like AP-1 and NRF2, implicating these factors in regulating enhancer activity during cardiac aging.\
    → Hypothesis: Sex-specific chromatin accessibility peaks contain distinct hormone receptor motifs, such as estrogen receptor alpha (ERα) motifs in females, which might explain differential gene regulation related to hormone signaling.

4.  **Co-binding Analysis**: Identify transcription factors potentially co-binding with histone modifications or accessible regions and assess whether their binding differs by age or sex.

    → Hypothesis: In aged LV tissue, the co-binding of H3K9me3 with cardiac transcription factors (e.g., GATA4) at specific promoter regions is reduced compared to young tissue, reflecting a loss of coordinated repression that affects cardiac function.\
    → Hypothesis: Females have distinct transcription factor co-binding patterns at accessible chromatin regions, particularly involving estrogen receptor motifs, influencing gene regulation in a sex-specific manner.\

This is not a final plan, but the start of a discussion!
